# render.yaml
databases:
  - name: decidim-db
    plan: basic-1gb  # pick a plan; you can start small and resize later

services:
  # Redis-compatible Key Value for Sidekiq
  - type: keyvalue
    name: decidim-redis
    maxmemoryPolicy: noeviction
    ipAllowList: []   # internal only

  # Web service (Rails + Puma)
  - type: web
    name: decidim-web
    runtime: ruby
    plan: standard
    buildCommand: |
      bundle config set deployment 'true'
      bundle config set without 'development test'
      bundle install --jobs=4 --retry=3
      rm -f bin/bundle bin/puma
      bundle binstubs bundler puma --force
      yarn install --frozen-lockfile
      RAILS_ENV=production bundle exec rails shakapacker:compile
      RAILS_ENV=production bundle exec rails assets:precompile
    preDeployCommand: |
      rm -f bin/bundle bin/puma
      bundle binstubs bundler puma --force
      bin/rails db:prepare
    startCommand: bundle exec puma -t 5:5 -p ${PORT:-3000} -e production
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RACK_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: "true"
      - key: RAILS_LOG_TO_STDOUT
        value: "1"
      - key: RAILS_MASTER_KEY      # paste in Render when prompted
        sync: false
      - key: SECRET_KEY_BASE       # generate in Render
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: decidim-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: decidim-redis
          property: connectionString
      - key: QUEUE_ADAPTER
        value: sidekiq
      - key: SIDEKIQ_CONCURRENCY
        value: "5"
      # Decidim basics
      - key: DECIDIM_APPLICATION_NAME
        value: "MDM PACA Participation"
      - key: DECIDIM_MAILER_SENDER
        value: "no-reply@mdm-paca-participation.org"
      # SMTP
      - key: SMTP_ADDRESS
        value: "smtp-relay.brevo.com"   # example
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_DOMAIN
        value: "mdm-paca-participation.org"
      - key: SMTP_USERNAME
        sync: false                 # set in the dashboard
      - key: SMTP_PASSWORD
        sync: false                 # set in the dashboard
      - key: SMTP_AUTHENTICATION
        value: "plain"
      - key: SMTP_STARTTLS_AUTO
        value: "true"
      # Active Storage (S3-compatible)
      - key: STORAGE_PROVIDER
        value: s3
      - key: AWS_REGION
        value: "eu-north-1"          # Paris region example
      - key: AWS_ACCESS_KEY_ID
        sync: false
      - key: AWS_SECRET_ACCESS_KEY
        sync: false
      - key: AWS_S3_BUCKET
        sync: false

  # Sidekiq worker
  - type: worker
    name: decidim-sidekiq
    runtime: ruby
    plan: starter
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: decidim-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: decidim-redis
          property: connectionString
      - key: QUEUE_ADAPTER
        value: sidekiq
      - key: SIDEKIQ_CONCURRENCY
        value: "5"

  # --- Cron jobs required by Decidim ---
  # Run reminders daily at 00:04 UTC
  - type: cron
    name: decidim-reminders
    runtime: ruby
    schedule: "4 0 * * *"
    buildCommand: bundle install
    startCommand: bundle exec rake decidim:reminders:all
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true  
      - key: DATABASE_URL
        fromDatabase:
          name: decidim-db
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: decidim-redis
          property: connectionString

  # Delete expired “download your data” files daily 00:00 UTC
  - type: cron
    name: decidim-delete-data-exports
    runtime: ruby
    schedule: "0 0 * * *"
    buildCommand: bundle install
    startCommand: bundle exec rake decidim:delete_download_your_data_files
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true  
      - key: DATABASE_URL
        fromDatabase:
          name: decidim-db
          property: connectionString

  # Weekly notifications digest every Sat 00:05 UTC
  - type: cron
    name: decidim-notifications-weekly
    runtime: ruby
    schedule: "5 0 * * 6"
    buildCommand: bundle install
    startCommand: bundle exec rake decidim:mailers:notifications_digest_weekly
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SECRET_KEY_BASE
        generateValue: true  
      - key: DATABASE_URL
        fromDatabase:
          name: decidim-db
          property: connectionString
